{% set version = "0.11.1" %}

package:
  name: trio-websocket
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/t/trio-websocket/trio-websocket-{{ version }}.tar.gz
    sha256: 18c11793647703c158b1f6e62de638acada927344d534e3c7628eedcb746839f
  - folder: src
    url: https://github.com/HyperionGray/trio-websocket/archive/refs/tags/{{ version }}.tar.gz
    sha256: 31b33561be82ea8f748ca2d8adaf3c45a2003c1a5e1550d7cf44e5a884564bce

build:
  number: 1
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - exceptiongroup
    - python >={{ python_min }}
    - trio >=0.11
    - wsproto >=0.14

test:
  source_files:
    - src/pytest.ini
    - src/tests
  imports:
    - trio_websocket
  commands:
    - pip check
    - cd src && pytest -vv --cov trio_websocket --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 95
  requires:
    - attrs >=19.2.0
    - pip
    - pytest >=4.6
    - pytest-cov
    - pytest-trio >=0.5.0
    - trustme
    - python {{ python_min }}

about:
  home: https://github.com/HyperionGray/trio-websocket
  summary: WebSocket library for Trio
  license: MIT
  # TODO: revisit if/after merge of https://github.com/HyperionGray/trio-websocket/pull/168
  license_file: src/LICENSE
  doc_url: https://trio-websocket.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
