{% set version = "0.12.0" %}

package:
  name: trio-websocket
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/t/trio-websocket/trio_websocket-{{ version }}.tar.gz
    sha256: d9bc17ee061c66c9abf62a08fe9f36949ad6be17eed281c3b979be9293f3df74
  - folder: src
    url: https://github.com/HyperionGray/trio-websocket/archive/refs/tags/{{ version }}.tar.gz
    sha256: eb0aabdc22a25585257473172336b3d9e1661f6a672541134e5d6de7020102cf

build:
  number: 0
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - exceptiongroup
    - python >={{ python_min }}
    - trio >=0.11
    - wsproto >=0.14

test:
  source_files:
    - src/pytest.ini
    - src/tests
  requires:
    - attrs >=19.2.0
    - pip
    - pytest >=4.6
    - pytest-cov
    - pytest-trio >=0.5.0
    - python {{ python_min }}
    - trustme
  imports:
    - trio_websocket
  commands:
    - pip check

about:
  home: https://github.com/HyperionGray/trio-websocket
  summary: WebSocket library for Trio
  license: MIT
  # TODO: revisit if/after merge of https://github.com/HyperionGray/trio-websocket/pull/168
  license_file: src/LICENSE
  doc_url: https://trio-websocket.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
