{% set version = "0.10.2" %}

package:
  name: trio-websocket
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/t/trio-websocket/trio-websocket-{{ version }}.tar.gz
    sha256: af13e9393f9051111300287947ec595d601758ce3d165328e7d36325135a8d62
  - folder: src
    url: https://github.com/HyperionGray/trio-websocket/archive/refs/tags/{{ version }}.tar.gz
    sha256: 00d6746724768b08f92f176d002f8bd6a4b66b989dddd8b952025590c1053b5e

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - exceptiongroup
    - python >=3.7
    - trio >=0.11
    - wsproto >=0.14

test:
  source_files:
    - src/pytest.ini
    - src/tests
  imports:
    - trio_websocket
  commands:
    - pip check
    - cd src && pytest -vv --cov trio_websocket --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 95
  requires:
    - attrs >=19.2.0
    - pip
    - pytest >=4.6
    - pytest-cov
    - pytest-trio >=0.5.0
    - trustme

about:
  home: https://github.com/HyperionGray/trio-websocket
  summary: WebSocket library for Trio
  license: MIT
  # TODO: revisit if/after merge of https://github.com/HyperionGray/trio-websocket/pull/168
  license_file: src/LICENSE
  doc_url: https://trio-websocket.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
