# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.12.1"

package:
  name: trio-websocket
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/trio-websocket/trio_websocket-${{ version }}.tar.gz
  sha256: d55ccd4d3eae27c494f3fdae14823317839bdcb8214d1173eacc4d42c69fc91b

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - exceptiongroup
    - python >=${{ python_min }}
    - trio >=0.11
    - wsproto >=0.14

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports: trio_websocket
  - files:
      recipe:
        - run_test.py
      source:
        - tests/
    requirements:
      run:
        - attrs >=19.2.0
        - pytest >=4.6
        - pytest-cov
        - pytest-trio >=0.5.0
        - python ${{ python_min }}.*
        - trustme
    script:
      - python run_test.py

about:
  summary: WebSocket library for Trio
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/python-trio/trio-websocket
  documentation: https://trio-websocket.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
